package org.bublapi.dent.notification.entity;

public enum NotificationType {
   APPOINTMENT_CREATED,
   APPOINTMENT_CANCELLED,
   APPOINTMENT_STATUS_CHANGED,
   APPOINTMENT_REMINDER,
   USER_REGISTERED,
   USER_ACTIVATED,
   USER_DEACTIVATED,
   PATIENT_CARD_LINKED,
   PATIENT_CARD_IS_BUSY
}
