server:
  port: 8080

spring:
  config:
    import: optional:file:./local.properties

  datasource:
    url: jdbc:postgresql://localhost:5433/bublapi_dent
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  
  rabbitmq:
    host: localhost
    port: 5672
    username: bublapi
    password: bublapi
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 5000
        default-requeue-rejected: false

  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 2592000000
