server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:./local.properties

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/bublapi_dent}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:bublapi}
    password: ${RABBITMQ_PASSWORD:bublapi}

    listener:
      simple:
        auto-startup: true
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 5000
        default-requeue-rejected: false

  mail:
    host: ${MAIL_HOST:smtp.timeweb.ru}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:}
    reply-to: ${MAIL_REPLY_TO:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
